spring:
  application:
    name: 04-irctc-booking

  datasource:
    url: jdbc:mysql://localhost:3306/5th_jan_2026_batch
    # url: jdbc:mysql://host.docker.internal:3306/5th_jan_2026_batch
    username: root
    password: Test@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  application:
    name: Payment Service
    description: IRCTC Payment Microservice
    version: 1.0.0

bootstrap:
  servers: localhost:9092

key:
  serializer: org.apache.kafka.common.serialization.StringSerializer

value:
  serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
