server:
  port: 8085

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: irctc-booking-service
              uri: http://localhost:8087
              predicates:
                - Path=/irctc/booking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true