spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb_dev
    username: root
    password: Test@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  zipkin:
    base-url: http://zipkin:9411
    enabled: true
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true
